#!/bin/csh -f
#
# @(#)$Header$
#
## HEADER ########################################################
#
# This script sets up the environment variables needed for compiling
# and linking to the filesetapi library.
#
##################################################################

if ( $?SMK_SUBSYS ) then
   
   #  Set directory names
   setenv FS_ROOT    $SMK_SUBSYS/filesetapi     # FileSetAPI source and root 
   setenv IOINC      $SMK_SUBSYS/ioapi_includes # I/O API include files

   if ( $?SMOKE_EXE ) then
      setenv  FS_BIN "$FS_ROOT/$SMOKE_EXE"
   endif

   #  Get system-specific flags
   source $SMK_SUBSYS/filesetapi/sysflags

else
   echo "ERROR: FileSetAPI \"Setup\" script requires setting of the SMK_SUBSYS"
   echo "       environment variable prior to using it."
   set status = 1

endif

exit( $status )
